apiVersion: v1
kind: Service
metadata:
  name: telemetry
  labels:
    app: telemetry
spec:
  selector:
    app: telemetry
  ports:
  - port: 1024
    targetPort: 1024
    name: feed
  - port: 3000
    targetPort: 3000
    name: frontend
  - port: 8080
    targetPort: 8080
    name: backend
